---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
- name: movie_fsd

outputs:
- name: package-output

run:
  path: movie-fsd/ci/tasks/package.sh

